name: github-actions

on:
  push:
    branches:
       - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Cache dependencies
        run: echo "Caching dependencies"
        with:
          cache-dependency-path: |
            sub-project/*.gradle*  
            sub-project/**/gradle-wrapper.properties

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run Tests
        run: ./gradlew test --no-daemon